CREATE TABLE IF NOT EXISTS `blog_type` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `title` varchar(255) NOT NULL COMMENT '分类名称',
    `slug` varchar(255) DEFAULT NULL COMMENT '分类别名',
    `description` text COMMENT '分类描述',
    `image` varchar(255) DEFAULT NULL COMMENT '分类图片',
    `sort` int(11) DEFAULT 0 COMMENT '排序',
    `status` varchar(20) DEFAULT '1' COMMENT '状态',
    `user_id` int(11) DEFAULT 0 COMMENT '创建者',
    `sys_tag` varchar(50) DEFAULT 'blog' COMMENT '系统标签',
    `created_at` int(11) NOT NULL COMMENT '创建时间',
    `updated_at` int(11) NOT NULL COMMENT '更新时间',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT '博客分类表';

CREATE TABLE IF NOT EXISTS `blog` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `title` varchar(255) NOT NULL COMMENT '博客标题',
    `slug` varchar(255) DEFAULT NULL COMMENT '博客别名',
    `desc` varchar(500) DEFAULT '' COMMENT '博客描述',
    `content` longtext NOT NULL COMMENT '博客内容',
    `image` varchar(255) DEFAULT NULL COMMENT '封面图片',
    `images` JSON DEFAULT NULL COMMENT '图片列表',
    `type_id` varchar(255) DEFAULT 0 COMMENT '分类ID',
    `last_type_id` int(11) DEFAULT 0 COMMENT '最后一级分类ID',
    `tags` varchar(500) DEFAULT '' COMMENT '标签',
    `views` int(11) DEFAULT 0 COMMENT '浏览量',
    `likes` int(11) DEFAULT 0 COMMENT '点赞数',
    `comments` int(11) DEFAULT 0 COMMENT '评论数',
    `sort` int(11) DEFAULT 0 COMMENT '排序',
    `status` varchar(20) DEFAULT 'draft' COMMENT '状态：draft草稿,published已发布,archived已归档',
    `is_top` tinyint(1) DEFAULT 0 COMMENT '是否置顶',
    `is_recommend` tinyint(1) DEFAULT 0 COMMENT '是否推荐',
    `user_id` int(11) DEFAULT 0 COMMENT '创建者',
    `admin_id` int(11) DEFAULT 0 COMMENT '管理员ID',
    `sys_tag` varchar(50) DEFAULT 'blog' COMMENT '系统标签',
    `created_at` int(11) NOT NULL COMMENT '创建时间',
    `updated_at` int(11) NOT NULL COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_type_id` (`type_id`),
    KEY `idx_status` (`status`),
    KEY `idx_user_id` (`user_id`),
    KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT '博客表';
